### ISSUE TITLE
vend add doesn't seem to add to .gitmodules

### ISSUE THREAD

**Issue by davedash** [jbalogh/vending-machine#1]
vend add seemed to just add the files from a git repo, but not actually make an entry in  .gitmodule:

https://github.com/mozilla/FlightDeck-lib/commit/cfb123c272087de920c89b3d0be782c4bb235461

**Comment by jbalogh** [comment]
How did you run it? I haven't had any issues with it doing the right
thing so far. This seems really odd since git should ignore another
directory with a .git.

On Thu, Jun 2, 2011 at 5:49 PM, davedash
reply@reply.github.com
wrote:

**Comment by davedash** [comment]
http://paste.pocoo.org/show/399873/

One thing that is different with flightdeck is the vendor is a submodule - but that may not make a difference.

**Comment by davedash** [comment]
workaround is to do vend -d . in the vendor directory.
